'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Bot, Check, ChevronDown, Copy, RotateCcw, Send, ThumbsDown, ThumbsUp, Trash2, X } from 'lucide-react';

type Msg={id:string;role:'user'|'assistant';content:string;feedback?:number|null};
type Config={publicId:string;name:string;statusText:string;avatarUrl:string|null;welcomeMessage:string;settings:{primaryColor:string;position:string;widgetSize:string;borderRadius:number;theme:string;placeholder:string;quickActionsJson:string;storeConversations:boolean}};

function markdown(text:string){return text.split('\n').map((line,i)=><span key={i}>{line}{i<text.split('\n').length-1&&<br/>}</span>)}

export default function ChatWidget({widgetId='demo',embedded=false}:{widgetId?:string;embedded?:boolean}){
 const [config,setConfig]=useState<Config|null>(null),[open,setOpen]=useState(embedded),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(false),[conversationId,setConversationId]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null),[error,setError]=useState('');
 const end=useRef<HTMLDivElement>(null);
 const visitor=useMemo(()=>{if(typeof window==='undefined')return 'server';const k=`chatnex_visitor_${widgetId}`;let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v},[widgetId]);
 useEffect(()=>{fetch(`/api/widget?id=${encodeURIComponent(widgetId)}`).then(r=>r.ok?r.json():null).then(setConfig).catch(()=>{})},[widgetId]);
 useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,loading]);
 async function send(value=text){const message=value.trim();if(!message||loading)return;setError('');setText('');setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',content:message}]);setLoading(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({widgetId,visitorId:visitor,conversationId:conversationId||undefined,message})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to respond.');if(d.conversationId)setConversationId(d.conversationId);setMessages(m=>[...m,{id:d.message.id,role:'assistant',content:d.message.content,feedback:null}]);}catch(e){setError(e instanceof Error?e.message:'Sorry, I\'m temporarily unable to respond.')}finally{setLoading(false)}}
 const actions=useMemo(()=>{try{return JSON.parse(config?.settings.quickActionsJson||'[]') as string[]}catch{return []}},[config]);
 const color=config?.settings.primaryColor||'#2563eb'; const radius=config?.settings.borderRadius??18; const dark=config?.settings.theme==='dark';
 const position=config?.settings.position==='bottom-left'?'left-5':'right-5'; const size=config?.settings.widgetSize==='small'?'w-[360px]':config?.settings.widgetSize==='large'?'w-[480px]':'w-[410px]'; const windowClass=embedded?'fixed inset-0':`fixed bottom-5 ${position}`;
 function clear(){setMessages([]);setConversationId(null);setError('')}
 async function copy(id:string,content:string){try{await navigator.clipboard?.writeText(content)}catch{}setCopied(id);setTimeout(()=>setCopied(null),1200)}
 async function feedback(messageId:string,rating:number){try{await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({widgetId,visitorId:visitor,messageId,rating})});setMessages(ms=>ms.map(m=>m.id===messageId?{...m,feedback:rating}:m))}catch{}}
 return <>{!embedded&&!open&&<button aria-label="Open ChatNex" onClick={()=>setOpen(true)} style={{backgroundColor:color}} className={`fixed bottom-5 ${position} z-50 grid h-14 w-14 place-items-center rounded-full text-white shadow-xl transition hover:scale-105`}><Bot/></button>}
 {open&&<section role="dialog" aria-modal="true" aria-label={`${config?.name||'ChatNex'} chatbot`} className={`${windowClass} z-50 flex flex-col overflow-hidden border shadow-2xl ${embedded?'h-full w-full':`h-[min(680px,calc(100vh-40px))] ${size} max-w-[calc(100vw-24px)]`} ${dark?'border-slate-700 bg-slate-950 text-slate-100':'border-slate-200 bg-white text-slate-900'}`} style={{borderRadius:embedded?0:radius}}>
 <header className={`flex items-center justify-between border-b px-4 py-3 ${dark?'border-slate-800 bg-slate-950':'border-slate-200 bg-white'}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center overflow-hidden rounded-xl text-white" style={{backgroundColor:color}}>{config?.avatarUrl?<img src={config.avatarUrl} alt="" className="h-full w-full object-cover"/>:<Bot size={18}/>}</div><div><div className={`font-semibold ${dark?'text-white':'text-slate-900'}`}>{config?.name||'ChatNex'}</div><div className="flex items-center gap-1 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-500"/>{config?.statusText||'Online'}</div></div></div><div className="flex gap-1"><button className={`rounded-lg p-2 ${dark?'hover:bg-slate-800':'hover:bg-slate-100'}`} onClick={clear} aria-label="Clear conversation"><RotateCcw size={16}/></button>{!embedded&&<button className={`rounded-lg p-2 ${dark?'hover:bg-slate-800':'hover:bg-slate-100'}`} onClick={()=>setOpen(false)} aria-label="Minimize"><ChevronDown size={18}/></button>}<button className={`rounded-lg p-2 ${dark?'hover:bg-slate-800':'hover:bg-slate-100'}`} onClick={()=>setOpen(false)} aria-label="Close"><X size={17}/></button></div></header>
 <div className={`flex-1 space-y-3 overflow-y-auto p-4 ${dark?'bg-slate-900':'bg-slate-50'}`}>
 {messages.length===0&&<div><div className={`rounded-2xl rounded-tl-md p-4 text-sm shadow-sm ${dark?'bg-slate-800 text-slate-100':'bg-white text-slate-800'}`}>{config?.welcomeMessage||"Hi! I'm ChatNex. How can I help you today?"}</div>{actions.length>0&&<div className="mt-4 grid gap-2">{actions.map(x=><button key={x} onClick={()=>send(x)} className={`rounded-xl border px-3 py-2 text-left text-sm transition ${dark?'border-slate-700 bg-slate-800 text-slate-200 hover:border-blue-500':'border-slate-200 bg-white text-slate-700 hover:border-blue-300 hover:bg-blue-50'}`}>{x}</button>)}</div>}</div>}
 {messages.map(m=><div key={m.id} className={`group relative max-w-[88%] rounded-2xl px-3 py-2.5 text-sm ${m.role==='user'?'ml-auto rounded-br-md text-white':`rounded-bl-md shadow-sm ${dark?'bg-slate-800 text-slate-100':'bg-white text-slate-800'}`}`} style={m.role==='user'?{backgroundColor:color}:undefined}><div className="whitespace-pre-wrap">{markdown(m.content)}</div>{m.role==='assistant'&&<><button onClick={()=>copy(m.id,m.content)} aria-label="Copy response" className={`absolute -bottom-7 right-0 rounded-md p-1 text-slate-400 opacity-0 transition group-hover:opacity-100 ${dark?'hover:bg-slate-700':'hover:bg-slate-200'}`}>{copied===m.id?<Check size={13}/>:<Copy size={13}/>}</button><div className={`absolute -bottom-7 left-0 flex gap-1 rounded-md p-1 ${dark?'bg-slate-800':'bg-white'}`}><button onClick={()=>feedback(m.id,1)} aria-label="Helpful" className={`p-1 ${m.feedback===1?'text-emerald-500':'text-slate-400'}`}><ThumbsUp size={13}/></button><button onClick={()=>feedback(m.id,-1)} aria-label="Not helpful" className={`p-1 ${m.feedback===-1?'text-red-500':'text-slate-400'}`}><ThumbsDown size={13}/></button></div></>}</div>)}
 {loading&&<div className={`w-fit rounded-2xl rounded-bl-md px-3 py-2 text-xs shadow-sm ${dark?'bg-slate-800 text-slate-400':'bg-white text-slate-500'}`}>{config?.name||'ChatNex'} is typing... <span className="animate-pulse">●●●</span></div>}{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div ref={end}/></div>
 <div className={`border-t p-3 ${dark?'border-slate-800 bg-slate-950':'border-slate-200 bg-white'}`}><div className={`flex items-end gap-2 rounded-xl border p-2 focus-within:border-blue-400 ${dark?'border-slate-700 bg-slate-900':'border-slate-200 bg-slate-50'}`}><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={1} maxLength={4000} aria-label="Message" placeholder={config?.settings.placeholder||'Type your message...'} className={`max-h-32 min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none ${dark?'text-slate-100':'text-slate-900'}`}/><button onClick={()=>send()} disabled={!text.trim()||loading} aria-label="Send message" className="rounded-lg p-2 text-white disabled:opacity-40" style={{backgroundColor:color}}><Send size={17}/></button></div><div className="mt-2 flex items-center justify-between text-[11px] text-slate-400"><span>{text.length}/4000 · Enter to send · Shift+Enter for newline</span><button onClick={clear} className="flex items-center gap-1 hover:text-slate-700"><Trash2 size={12}/>Clear</button></div></div>
 </section>}</>}
