'use client';
import { useEffect, useState } from 'react';
import { BarChart3, BookOpen, Bot, FileQuestion, LogOut, MessageSquare, Palette, Save, Settings, Trash2 } from 'lucide-react';

type Data={conversations:number;messages:number;averageMessages:number;knowledge:number;faqs:number;recent:any[];events:any[]};
type SettingsData={name:string;statusText:string;welcomeMessage:string;settings:any};
const nav=[['Overview',BarChart3],['Conversations',MessageSquare],['Knowledge Base',BookOpen],['FAQs',FileQuestion],['Appearance',Palette],['Bot Settings',Bot],['Analytics',BarChart3],['Settings',Settings]] as const;

export default function AdminDashboard(){
 const [tab,setTab]=useState('Overview'),[data,setData]=useState<Data|null>(null),[knowledge,setKnowledge]=useState<any[]>([]),[faqs,setFaqs]=useState<any[]>([]),[conversations,setConversations]=useState<any[]>([]),[config,setConfig]=useState<SettingsData|null>(null),[status,setStatus]=useState('');
 async function load(){const [a,k,f,c,s]=await Promise.all([fetch('/api/analytics'),fetch('/api/knowledge'),fetch('/api/faqs'),fetch('/api/conversations'),fetch('/api/settings')]);setData(await a.json());setKnowledge(await k.json());setFaqs(await f.json());setConversations(await c.json());setConfig(await s.json());}
 useEffect(()=>{load()},[]);
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'logout'})});location.href='/admin/login'}
 async function remove(url:string,id:string){if(!confirm('Delete this item?'))return;await fetch(url,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});load()}
 async function saveSettings(e:React.FormEvent){e.preventDefault();if(!config)return;setStatus('Saving…');const r=await fetch('/api/widget',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({widgetId:'demo',name:config.name,statusText:config.statusText,welcomeMessage:config.welcomeMessage,settings:config.settings})});setStatus(r.ok?'Saved':'Save failed');await load();setTimeout(()=>setStatus(''),1800)}
 return <main className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r bg-white p-4 md:block"><div className="mb-8 px-3 text-xl font-bold tracking-tight">CHATNEX</div>{nav.map(([name,Icon])=><button key={name} onClick={()=>setTab(name)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${tab===name?'bg-blue-50 text-blue-700':'text-slate-600 hover:bg-slate-50'}`}><Icon size={17}/>{name}</button>)}<button onClick={logout} className="mt-8 flex items-center gap-3 px-3 py-2 text-sm text-slate-500 hover:text-slate-900"><LogOut size={17}/>Sign out</button></aside><section className="md:ml-64"><header className="sticky top-0 z-10 border-b bg-white/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3"><select value={tab} onChange={e=>setTab(e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-sm md:hidden">{nav.map(([n])=><option key={n}>{n}</option>)}</select><div><h1 className="text-2xl font-semibold">{tab}</h1><p className="mt-1 text-sm text-slate-500">Manage your ChatNex installation.</p></div></div></header><div className="p-5 md:p-7">
 {tab==='Overview'&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Conversations',data?.conversations],['Messages',data?.messages],['Avg. messages',data?.averageMessages],['Knowledge',data?.knowledge],['FAQs',data?.faqs]].map(([a,b])=><div key={String(a)} className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">{a}</div><div className="mt-2 text-3xl font-semibold">{b??'—'}</div></div>)}</div><div className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Recent conversations</h2><div className="mt-3 divide-y">{data?.recent?.map((c:any)=><div key={c.id} className="flex items-center justify-between py-3 text-sm"><span className="font-mono text-slate-600">{c.id.slice(0,14)}…</span><span className="text-slate-500">{c.messages.length} messages</span></div>)}</div></div></>}
 {tab==='Conversations'&&<Panel title="Conversations"><div className="space-y-3">{conversations.map(c=><details key={c.id} className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">{c.id} <span className="text-slate-400">· {c.messages.length} messages</span></summary><div className="mt-4 space-y-2">{c.messages.map((m:any)=><div key={m.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{m.role}:</b> {m.content}</div>)}</div><button onClick={()=>remove('/api/conversations',c.id)} className="mt-3 flex items-center gap-1 text-xs text-red-600"><Trash2 size={13}/>Delete</button></details>)}</div></Panel>}
 {tab==='Knowledge Base'&&<Panel title="Knowledge Base"><CreateKnowledge onDone={load}/><div className="mt-5 space-y-3">{knowledge.map(k=><div key={k.id} className="rounded-xl border p-4"><div className="flex justify-between gap-4"><div><b>{k.title}</b><div className="text-xs text-slate-500">{k.category} · {k.enabled?'Enabled':'Disabled'}</div></div><button onClick={()=>remove('/api/knowledge',k.id)} className="text-red-600"><Trash2 size={15}/></button></div><p className="mt-2 text-sm text-slate-600">{k.content}</p></div>)}</div></Panel>}
 {tab==='FAQs'&&<Panel title="FAQs"><CreateFaq onDone={load}/><div className="mt-5 space-y-3">{faqs.map(f=><div key={f.id} className="rounded-xl border p-4"><div className="flex justify-between gap-4"><b>{f.question}</b><button onClick={()=>remove('/api/faqs',f.id)} className="text-red-600"><Trash2 size={15}/></button></div><p className="mt-2 text-sm text-slate-600">{f.answer}</p></div>)}</div></Panel>}
 {config&&['Appearance','Bot Settings','Settings'].includes(tab)&&<form onSubmit={saveSettings} className="max-w-3xl rounded-2xl border bg-white p-6"><h2 className="font-semibold">{tab} configuration</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Bot name"><input value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></Field><Field label="Status"><input value={config.statusText} onChange={e=>setConfig({...config,statusText:e.target.value})}/></Field><Field label="Primary color"><input type="color" value={config.settings.primaryColor} onChange={e=>setConfig({...config,settings:{...config.settings,primaryColor:e.target.value}})} className="h-11 w-full"/></Field><Field label="Theme"><select value={config.settings.theme} onChange={e=>setConfig({...config,settings:{...config.settings,theme:e.target.value}})}><option>system</option><option>light</option><option>dark</option></select></Field><Field label="Position"><select value={config.settings.position} onChange={e=>setConfig({...config,settings:{...config.settings,position:e.target.value}})}><option>bottom-right</option><option>bottom-left</option></select></Field><Field label="Placeholder"><input value={config.settings.placeholder} onChange={e=>setConfig({...config,settings:{...config.settings,placeholder:e.target.value}})}/></Field></div><Field label="Welcome message"><textarea value={config.welcomeMessage} onChange={e=>setConfig({...config,welcomeMessage:e.target.value})}/></Field><Field label="System prompt"><textarea value={config.settings.systemPrompt} onChange={e=>setConfig({...config,settings:{...config.settings,systemPrompt:e.target.value}})}/></Field><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={config.settings.storeConversations} onChange={e=>setConfig({...config,settings:{...config.settings,storeConversations:e.target.checked}})}/> Store conversations</label><button className="mt-6 flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white"><Save size={16}/>{status||'Save changes'}</button></form>}
 {tab==='Analytics'&&<Panel title="Analytics"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries((data?.events||[]).reduce((a:any,e:any)=>(a[e.type]=(a[e.type]||0)+1,a),{})).map(([k,v])=><div key={k} className="rounded-xl border p-4"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 text-2xl font-semibold">{String(v)}</div></div>)}</div></Panel>}
 </div></section></main>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">{title}</h2>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block text-sm text-slate-600">{label}<div className="mt-1">{children}</div></label>}
function CreateKnowledge({onDone}:{onDone:()=>void}){const [title,setTitle]=useState(''),[content,setContent]=useState(''),[category,setCategory]=useState('General'),[keywords,setKeywords]=useState('');async function add(e:React.FormEvent){e.preventDefault();await fetch('/api/knowledge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({widgetId:'demo',title,content,category,keywords,enabled:true})});setTitle('');setContent('');setKeywords('');onDone()}return <form onSubmit={add} className="grid gap-2 rounded-xl bg-slate-50 p-4 md:grid-cols-2"><input required placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Category" value={category} onChange={e=>setCategory(e.target.value)}/><input className="md:col-span-2" placeholder="Keywords" value={keywords} onChange={e=>setKeywords(e.target.value)}/><textarea required className="md:col-span-2" placeholder="Knowledge content" value={content} onChange={e=>setContent(e.target.value)}/><button className="w-fit rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Add entry</button></form>}
function CreateFaq({onDone}:{onDone:()=>void}){const [question,setQuestion]=useState(''),[answer,setAnswer]=useState('');async function add(e:React.FormEvent){e.preventDefault();await fetch('/api/faqs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({widgetId:'demo',question,answer,category:'General',enabled:true})});setQuestion('');setAnswer('');onDone()}return <form onSubmit={add} className="grid gap-2 rounded-xl bg-slate-50 p-4"><input required placeholder="Question" value={question} onChange={e=>setQuestion(e.target.value)}/><textarea required placeholder="Answer" value={answer} onChange={e=>setAnswer(e.target.value)}/><button className="w-fit rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Add FAQ</button></form>}
